### PR TITLE
Reconstruct the whole PalEdit, i18n support, add characters, use GvasFile to improve performance

### PR DESCRIPTION
**Pull request by magicbear**
- Reconstruct the whole PalEdit, make it Objectification
- Support add new pal from #78 
- Player sav parse
- Fix for losing all learned skills on edited Pals from #76

### CODE REVIEW

**Comment by magicbear** [comment]
> When using your version, I've got an error when trying to write changes to a save. Here's the debug output:
> 
> > Exception in Tkinter callback
> > Traceback (most recent call last):
> > File "/usr/lib/python3.11/tkinter/**init**.py", line 1948, in **call**
> > return self.func(*args)
> > ^^^^^^^^^^^^^^^^
> > File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 485, in savefile
> > self.root.update()
> > ^^^^^^^^^
> > AttributeError: 'PalEdit' object has no attribute 'root'

fixed, have bug for merge #76

**Comment by AngryBirdz** [comment]
I've just tested your [latest commit](https://github.com/EternalWraith/PalEdit/pull/87/commits/0037ec9fb41d17a3c58af2d6bf7174dcb17e1036) and now I get this error when I try to open a Level.sav file:

> Opening file /home/angrybird/Level.sav
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
>     return self.func(*args)
>            ^^^^^^^^^^^^^^^^
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 384, in loadfile
>     self.loaddata(gvas_file)
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 418, in loaddata
>     self.loadpal(paldata)
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 423, in loadpal
>     self.players = self.palguidmanager.GetPlayerslist()
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'PalGuid' object has no attribute 'GetPlayerslist'

**Comment by magicbear** [comment]
> I've just tested your [latest commit](https://github.com/EternalWraith/PalEdit/pull/87/commits/0037ec9fb41d17a3c58af2d6bf7174dcb17e1036) and now I get this error when I try to open a Level.sav file:
> 
> > Opening file /home/angrybird/Level.sav
> > Exception in Tkinter callback
> > Traceback (most recent call last):
> > File "/usr/lib/python3.11/tkinter/**init**.py", line 1948, in **call**
> > return self.func(*args)
> > ^^^^^^^^^^^^^^^^
> > File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 384, in loadfile
> > self.loaddata(gvas_file)
> > File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 418, in loaddata
> > self.loadpal(paldata)
> > File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 423, in loadpal
> > self.players = self.palguidmanager.GetPlayerslist()
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > AttributeError: 'PalGuid' object has no attribute 'GetPlayerslist'

I think you may be download for the old commit, just git clone https://github.com/magicbear/PalEdit.git and git checkout [objectification](https://github.com/magicbear/PalEdit)

**Comment by AngryBirdz** [comment]
Cloning the right git fixed my loading problem.
I noticed a few errors in the log while using PalEdit.

Those errors popped while loading the save:

> Error occured: 'PlantSlime_Flower'
> Error occured: 'Female_People02'

I got those errors when I was selecting equipped abilities for a pal:

> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
>     return self.func(*args)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/tkinter/__init__.py", line 4013, in __call__
>     self.__callback(self.__value, *args)
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 887, in <lambda>
>     tk.OptionMenu(equipFrame, self.attacks[2], *self.attackops, command=lambda evt: self.changeattack(2))
>                                                                                     ^^^^^^^^^^^^^^^^^^^^
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 280, in changeattack
>     self.refresh(i)
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 659, in refresh
>     self.setAttackCols()
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 125, in setAttackCols
>     basecol = PalInfo.PalElements[PalInfo.AttackTypes[v]]
>               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
> KeyError: ''
> 
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
>     return self.func(*args)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/tkinter/__init__.py", line 4013, in __call__
>     self.__callback(self.__value, *args)
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 887, in <lambda>
>     tk.OptionMenu(equipFrame, self.attacks[2], *self.attackops, command=lambda evt: self.changeattack(2))
>                                                                                     ^^^^^^^^^^^^^^^^^^^^
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 280, in changeattack
>     self.refresh(i)
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 659, in refresh
>     self.setAttackCols()
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 125, in setAttackCols
>     basecol = PalInfo.PalElements[PalInfo.AttackTypes[v]]
>               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
> KeyError: ''

Switching to another player does not work and I get this error:

> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
>     return self.func(*args)
>            ^^^^^^^^^^^^^^^^
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 288, in onselect
>     self.updatestats(self.editindex)
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 596, in updatestats
>     pal = self.palbox[self.players[self.current.get()]][e]
>           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
> IndexError: list index out of range
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
>     return self.func(*args)
>            ^^^^^^^^^^^^^^^^
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 288, in onselect
>     self.updatestats(self.editindex)
>   File "/home/angrybird/.local/bin/PalEdit/PalEdit.py", line 596, in updatestats
>     pal = self.palbox[self.players[self.current.get()]][e]
>           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
> IndexError: list index out of range

**Comment by VoltageMiner** [comment]
@magicbear I have a few issues with your fork. I'm posting this here because I cannot open an issue on your fork for some reason. 

1) requirements.txt is missing pyperclip so it cannot be compiled without editing it or manually installing it. This is an issue with the main repository anyway. Building the executable does work after making the change, but I cannot run it as it tries to look for the resources in my temp files instead of the folder the executable is in for some reason. I don't have this issue with the main repository. I'm running Python 3.12.1.

2) Running the script directly via python PalEdit.py does work, but I noticed that the MossandaIcon that appears on startup briefly appears then disappears. The Icon sticks around until changed using the main repository version.

3) I noticed that your fix for #76 seems to not work anymore for me. It probably got changed in a commit somewhere.

**Comment by Snowstar38** [comment]
@VoltageMiner if you're talking about PR#76 that's mine not theirs, and I did make some changes to it. Feel free to comment on it and I can try to work with you to figure out why it isn't working anymore for you, if you're talking about my version ofc.

**Comment by VoltageMiner** [comment]
> @VoltageMiner if you're talking about PR#76 that's mine not theirs, and I did make some changes to it. Feel free to comment on it and I can try to work with you to figure out why it isn't working anymore for you, if you're talking about my version ofc.

No worries! I was referring to the fix @magicbear implemented that was referencing #76 .

**Review by Cr4nkSt4r — COMMENTED** [review]
The image itself exists already, it's just named wrong. So adding this image, instead of renaming isn't the best solution I would think.
Current name is [Reptyro Cryst.png](https://github.com/EternalWraith/PalEdit/blob/main/resources/Reptyro%20Cryst.png)

**Comment by EternalWraith** [comment]
Hey @magicbear could you add me on discord my username is Brawlrounder

**Pull request merged**
